language: objective-c
osx_image: xcode8.2
script: xctool -project JLRoutes.xcodeproj -scheme 'JLRoutes' -configuration Debug -sdk iphonesimulator -arch i386 test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
